### ISSUE TITLE
does not build. source files in in wrong locations. 

### ISSUE THREAD

**Issue by justin-romano** [libyal/libmdmp#1]
.\build.ps1
Microsoft (R) Build Engine Version 3.5.30729.9034
[Microsoft .NET Framework, Version 2.0.50727.9040]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

c1 : fatal error C1083: Cannot open source file: '..\..\libcerror\libcerror_error.c': No such file or directory
c1 : fatal error C1083: Cannot open source file: '..\..\libcerror\libcerror_system.c': No such file or directory
c1 : fatal error C1083: Cannot open source file: '..\..\libcerror\libcerror_support.c': No such file or directory

**Comment by joachimmetz** [comment]
Read this https://github.com/libyal/libmdmp/wiki/Building#read-first

.\build.ps1 is not a recommended build method.

Also you likely want to read https://github.com/libyal/libmdmp/blob/master/README, I don't think this is the project you are looking for.
