### ISSUE TITLE
Reading RVAs using libdmp_* functions

### ISSUE THREAD

**Issue by GitSparTV** [libyal/libmdmp#3]
Hi, I'm currently using this library to read mdmp files, currently I implemented reading modules stream and stopped at `ModuleNameRva`.
As I understand the position of RVA is relative to the whole file not the stream but I can't find function among `libdmp_*` library that would seek and read data in file.
What am I missing?

**Comment by joachimmetz** [comment]
Per README: Note that this project currently only focuses on the analysis of the format.

so the functionality you are looking for might not be there

**Comment by GitSparTV** [comment]
I thought that the analysis though, alright, what would you recommend here: `std::` functions or `libmdmp_io_handle_seek_segment_offset`/`libmdmp_io_handle_read_segment_data` or `libbfio_file_io_handle_seek_offset`/`libbfio_file_io_handle_read_buffer`?

**Comment by joachimmetz** [comment]
@GitSparTV this is a C (not C++) library so if you're planning to extend the library than using `std::` is not an option. If you are using this in a larger project that is up to you.

`libbfio_file` is a general purpose file IO back-end in libbfio, not need to use them directly. In the library you can use the `libbfio_handle` functions instead.

`libmdmp_io_handle_seek_segment_offset/libmdmp_io_handle_read_segment_data` (from the top of my head) are callback functions for `libfdata_stream` used in the library.

**Comment by GitSparTV** [comment]
Sorry by `std::` I meant standard C libraries with `fread`, `fseek`, `fopen`.
I managed to finish the project with them.
Thanks for the library.

**Comment by joachimmetz** [comment]
Good to hear you managed to finish the project with them. I assume this issue can be closed then.

For context libbfio_handle is the preferred method inside the library, so that the library can interact with e.g. Python file-like objects as well without modification.

**Comment by GitSparTV** [comment]
Yeah, I might change it to that io handler later.
Here is the result:
https://github.com/GitSparTV/gg.gmod-bot-public/tree/main/mdmp
![image](https://user-images.githubusercontent.com/5685050/106297819-30ce2500-6264-11eb-8ce3-f76fac76504c.png)
